### ISSUE TITLE
Network Traffic Visualization

### ISSUE THREAD

**Issue by saada** [saada/container-hive#8]
https://github.com/joeferner/node-shark

**Comment by saada** [comment]
https://github.com/docker/docker/issues/20224

**Comment by saada** [comment]
http://10sa.com/sql_stories/?p=1145

**Comment by saada** [comment]
https://docs.tenable.com/pvs/deployment/Content/DockerMonitoredInterfaces.htm

**Comment by saada** [comment]
http://searchcloudsecurity.techtarget.com/tip/How-to-inspect-Docker-container-traffic-for-potential-threats

**Comment by greengooner** [comment]
Its probably a bit further down the stack than anticipated but I finally had a chance to toy around with code on sockets and packet capture, looks like it might possibly be a way forward but I'm still testing it out.

http://www.binarytides.com/python-packet-sniffer-code-linux/ 
https://docs.python.org/2/library/socket.html

**Comment by saada** [comment]
Closing this now that it's working
